include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - lib/l10n/gen/**
    - build/**
    - macos/**
    - linux/**
    - windows/**
    - web/**
linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
    use_key_in_widget_constructors: true
    always_declare_return_types: true
    lines_longer_than_80_chars: false