include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false
    strict-raw-types: false
    strict-inference: false
  errors:
    # 降低噪音/团队约定类
    public_member_api_docs: info
    avoid_field_initializers_in_const_classes: info
    unnecessary_breaks: info
    flutter_style_todos: info
    sort_pub_dependencies: info
    parameter_assignments: info
    no_default_cases: info

    # 保持关键问题级别（使用 flutter_lints 默认）
    dead_code: warning
    unused_import: warning
    unused_local_variable: warning

linter:
  rules:
    # 可按需覆盖或关闭个别 lint（默认继承 flutter_lints）
    # - prefer_const_constructors
    # - avoid_equals_and_hash_code_on_mutable_classes